/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogCreateRouteImport } from './routes/blog/create'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as BlogEditIdRouteImport } from './routes/blog/edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCreateRoute = BlogCreateRouteImport.update({
  id: '/blog/create',
  path: '/blog/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditIdRoute = BlogEditIdRouteImport.update({
  id: '/blog/edit/$id',
  path: '/blog/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/create': typeof BlogCreateRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/edit/$id': typeof BlogEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/create': typeof BlogCreateRoute
  '/blog': typeof BlogIndexRoute
  '/blog/edit/$id': typeof BlogEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/blog/$id': typeof BlogIdRoute
  '/blog/create': typeof BlogCreateRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/edit/$id': typeof BlogEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/blog/$id'
    | '/blog/create'
    | '/blog/'
    | '/blog/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/blog/$id'
    | '/blog/create'
    | '/blog'
    | '/blog/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/blog/$id'
    | '/blog/create'
    | '/blog/'
    | '/blog/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  BlogIdRoute: typeof BlogIdRoute
  BlogCreateRoute: typeof BlogCreateRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogEditIdRoute: typeof BlogEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/create': {
      id: '/blog/create'
      path: '/blog/create'
      fullPath: '/blog/create'
      preLoaderRoute: typeof BlogCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/edit/$id': {
      id: '/blog/edit/$id'
      path: '/blog/edit/$id'
      fullPath: '/blog/edit/$id'
      preLoaderRoute: typeof BlogEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  BlogIdRoute: BlogIdRoute,
  BlogCreateRoute: BlogCreateRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogEditIdRoute: BlogEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
